[changelog]
header = """
# Proteus Player
You can find the binaries associated with this release for Linux, Windows, and macOS on the bottom of the page.

## Changelog
"""
body = """
{% if version %}
### {{ version }} - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}
### Unreleased
{% endif %}
{% for group, commits in commits | group_by(attribute="group") %}
#### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | upper_first }}{% if commit.id %} ({{ commit.id | truncate(length=7, end="") }}){% endif %}
{% endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
tag_pattern = "proteus-player-v[0-9].*"
sort_commits = "oldest"

commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Refactoring" },
  { message = "^docs", group = "Documentation" },
  { message = "^test", group = "Tests" },
  { message = "^build", group = "Build" },
  { message = "^ci", group = "CI" },
  { message = "^chore", group = "Chores" },
  { body = ".*breaking.*", group = "Breaking Changes" },
  { message = ".*", group = "Other" },
]
